apiVersion: v1
kind: Secret
metadata:
  name: mymicro-secret
  namespace: mymicro
type: Opaque
stringData:
  USER_MONGO_URI: "mongodb://mongo:27017/userdb"
  PRODUCT_MONGO_URI: "mongodb://mongo:27017/productdb"
  ORDER_MONGO_URI: "mongodb://mongo:27017/orderdb"
