apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: mymicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: sohaib22/mymicro-user-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: mymicro-config
                  key: USER_SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mymicro-secret
                  key: USER_MONGO_URI
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: mymicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: sohaib22/mymicro-product-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: mymicro-config
                  key: PRODUCT_SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mymicro-secret
                  key: PRODUCT_MONGO_URI
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: mymicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: sohaib22/mymicro-order-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: mymicro-config
                  key: ORDER_SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mymicro-secret
                  key: ORDER_MONGO_URI
