apiVersion: v1
kind: Secret
metadata:
  name: mymicro-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  USER_MONGO_URI: {{ .Values.secret.userMongoUri | quote }}
  PRODUCT_MONGO_URI: {{ .Values.secret.productMongoUri | quote }}
  ORDER_MONGO_URI: {{ .Values.secret.orderMongoUri | quote }}
