{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $svc.service.port }}
      targetPort: {{ $svc.service.targetPort }}
---
{{- end }}
