name: Deploy Microservices to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check cluster
        run: |
          kubectl get nodes
          kubectl config current-context
          minikube status

      - name: Create namespace
        run: |
          kubectl create namespace mymicro --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply base files
        run: |
          kubectl apply -f app-secret.yaml -n mymicro
          kubectl apply -f app-configmap.yaml -n mymicro
          kubectl apply -f quota.yaml -n mymicro

      - name: Recreate mongo service and storage
        run: |
          kubectl delete svc mongo -n mymicro --ignore-not-found=true
          kubectl delete deployment mongo -n mymicro --ignore-not-found=true
          kubectl apply -f mongo-persistent.yaml -n mymicro

      - name: Recreate app deployments
        run: |
          kubectl delete deploy user-service -n mymicro --ignore-not-found=true
          kubectl delete deploy product-service -n mymicro --ignore-not-found=true
          kubectl delete deploy order-service -n mymicro --ignore-not-found=true
          kubectl delete deploy frontend -n mymicro --ignore-not-found=true
          kubectl apply -f apps.yaml -n mymicro

      - name: Reset and enable ingress
        run: |
          minikube addons disable ingress || true
          kubectl delete namespace ingress-nginx --ignore-not-found=true || true
          minikube addons enable ingress
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=300s

      - name: Apply network policy
        run: |
          kubectl apply -f networkpolicy.yaml -n mymicro

      - name: Recreate ingress
        run: |
          kubectl delete ingress mymicro-ingress -n mymicro --ignore-not-found=true
          kubectl apply -f ingress.yaml -n mymicro

      - name: Apply hpa
        run: |
          kubectl apply -f hpa.yaml -n mymicro

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/user-service -n mymicro --timeout=180s
          kubectl rollout status deployment/product-service -n mymicro --timeout=180s
          kubectl rollout status deployment/order-service -n mymicro --timeout=180s
          kubectl rollout status deployment/frontend -n mymicro --timeout=180s

      - name: Show resources
        run: |
          kubectl get pods -n mymicro -o wide
          kubectl get svc -n mymicro
          kubectl get ingress -n mymicro
