name: Deploy Order Service

on:
  push:
    branches: [ "main" ]
    paths:
      - "orderservice/**"
      - ".github/workflows/order-service.yml"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t sohaib22/mymicro-order-service:${{ github.sha }} ./orderservice
          docker push sohaib22/mymicro-order-service:${{ github.sha }}

      - name: Update Deployment
        run: |
          kubectl set image deployment/order-service order-service=sohaib22/mymicro-order-service:${{ github.sha }} -n mymicro

      - name: Verify
        run: kubectl rollout status deployment/order-service -n mymicro
